/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventas;


/**
 *
 * @author Jessy
 */
public class JFLogin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public JFLogin() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdminsitrador = new javax.swing.JLabel();
        lblTexto1 = new javax.swing.JLabel();
        lblTexto2 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblContrasenia = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContrasenia = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(410, 355));
        getContentPane().setLayout(null);

        lblAdminsitrador.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblAdminsitrador.setText("Administrador");
        getContentPane().add(lblAdminsitrador);
        lblAdminsitrador.setBounds(180, 40, 100, 17);

        lblTexto1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblTexto1.setText("Para poder ingresar al sistema, usted debe estar  registrado previamente.");
        getContentPane().add(lblTexto1);
        lblTexto1.setBounds(30, 70, 420, 14);

        lblTexto2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblTexto2.setText("Por favor digite su usuario y contraseña.");
        getContentPane().add(lblTexto2);
        lblTexto2.setBounds(30, 100, 230, 14);

        lblUsuario.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblUsuario.setText("Usuario:");
        getContentPane().add(lblUsuario);
        lblUsuario.setBounds(100, 150, 60, 17);

        lblContrasenia.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblContrasenia.setText("Contraseña:");
        getContentPane().add(lblContrasenia);
        lblContrasenia.setBounds(100, 200, 70, 17);

        txtUsuario.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(190, 150, 170, 23);

        txtContrasenia.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        getContentPane().add(txtContrasenia);
        txtContrasenia.setBounds(190, 200, 170, 23);

        btnIngresar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ingresar_admin.png"))); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar);
        btnIngresar.setBounds(190, 260, 120, 40);

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/admin_cerrar.png"))); // NOI18N
        getContentPane().add(btnCerrar);
        btnCerrar.setBounds(450, 0, 30, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/fondo_CCCli _Admin.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 480, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        JDVentas obj=new JDVentas(this,true);
        obj.show();
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblAdminsitrador;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblTexto1;
    private javax.swing.JLabel lblTexto2;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtContrasenia;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
