/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.ingswii.vista;

/**
 *
 * @author Jessy
 */
public class FGestionarProducto extends javax.swing.JFrame {

    /**
     * Creates new form FBProducto
     */
    public FGestionarProducto() {
        initComponents();
        setSize(885, 460);//dar tamano fijo a la pantalla
        setLocationRelativeTo(null); //centrar la pantala        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlProducto = new javax.swing.JPanel();
        pnlBusqueda = new javax.swing.JPanel();
        rdNombre = new javax.swing.JRadioButton();
        rdCodigo = new javax.swing.JRadioButton();
        pnlGT = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        cbGrupo = new javax.swing.JComboBox<>();
        pnlLista = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dgvDatos = new javax.swing.JTable();
        pnlAcciones = new javax.swing.JPanel();
        lblStock = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblSerie = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        txtSerie = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        pnlOpciones = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pnlProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        pnlProducto.setLayout(null);

        pnlBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modo Búsqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        rdNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdNombre.setText("Nombre");

        rdCodigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdCodigo.setText("Código");

        javax.swing.GroupLayout pnlBusquedaLayout = new javax.swing.GroupLayout(pnlBusqueda);
        pnlBusqueda.setLayout(pnlBusquedaLayout);
        pnlBusquedaLayout.setHorizontalGroup(
            pnlBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBusquedaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdNombre)
                    .addComponent(rdCodigo))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pnlBusquedaLayout.setVerticalGroup(
            pnlBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBusquedaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(rdNombre)
                .addGap(18, 18, 18)
                .addComponent(rdCodigo)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnlProducto.add(pnlBusqueda);
        pnlBusqueda.setBounds(16, 30, 140, 130);

        pnlGT.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        pnlGT.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Grupo:");
        pnlGT.add(jLabel1);
        jLabel1.setBounds(10, 20, 37, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Tipo:");
        pnlGT.add(jLabel2);
        jLabel2.setBounds(10, 70, 28, 15);

        cbTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlGT.add(cbTipo);
        cbTipo.setBounds(70, 70, 170, 23);

        cbGrupo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlGT.add(cbGrupo);
        cbGrupo.setBounds(70, 20, 170, 23);

        pnlProducto.add(pnlGT);
        pnlGT.setBounds(160, 38, 250, 120);

        getContentPane().add(pnlProducto);
        pnlProducto.setBounds(10, 11, 420, 170);

        pnlLista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        pnlLista.setLayout(null);

        dgvDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(dgvDatos);

        pnlLista.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 560, 200);

        getContentPane().add(pnlLista);
        pnlLista.setBounds(10, 190, 580, 220);

        pnlAcciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        pnlAcciones.setLayout(null);

        lblStock.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblStock.setText("Stock:");
        pnlAcciones.add(lblStock);
        lblStock.setBounds(20, 300, 50, 15);

        lblCodigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCodigo.setText("Código:");
        pnlAcciones.add(lblCodigo);
        lblCodigo.setBounds(20, 30, 50, 15);

        lblTipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTipo.setText("Tipo:");
        pnlAcciones.add(lblTipo);
        lblTipo.setBounds(20, 60, 50, 15);

        lblSerie.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSerie.setText("Serie:");
        pnlAcciones.add(lblSerie);
        lblSerie.setBounds(20, 90, 50, 15);

        lblModelo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblModelo.setText("Modelo:");
        pnlAcciones.add(lblModelo);
        lblModelo.setBounds(20, 120, 50, 15);

        lblMarca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMarca.setText("Marca:");
        pnlAcciones.add(lblMarca);
        lblMarca.setBounds(20, 150, 50, 15);

        lblPrecio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPrecio.setText("Precio:");
        pnlAcciones.add(lblPrecio);
        lblPrecio.setBounds(20, 180, 50, 15);

        lblDescripcion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDescripcion.setText("Descripción:");
        pnlAcciones.add(lblDescripcion);
        lblDescripcion.setBounds(20, 210, 70, 15);

        txtDescripcion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnlAcciones.add(txtDescripcion);
        txtDescripcion.setBounds(90, 210, 160, 80);

        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnlAcciones.add(txtCodigo);
        txtCodigo.setBounds(90, 30, 160, 21);

        txtTipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnlAcciones.add(txtTipo);
        txtTipo.setBounds(90, 60, 160, 21);

        txtSerie.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnlAcciones.add(txtSerie);
        txtSerie.setBounds(90, 90, 160, 21);

        txtModelo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnlAcciones.add(txtModelo);
        txtModelo.setBounds(90, 120, 160, 21);

        txtMarca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnlAcciones.add(txtMarca);
        txtMarca.setBounds(90, 150, 160, 21);

        txtStock.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnlAcciones.add(txtStock);
        txtStock.setBounds(90, 300, 90, 21);

        txtPrecio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnlAcciones.add(txtPrecio);
        txtPrecio.setBounds(90, 180, 160, 21);

        btnOK.setText("OK");
        pnlAcciones.add(btnOK);
        btnOK.setBounds(90, 350, 47, 23);

        getContentPane().add(pnlAcciones);
        pnlAcciones.setBounds(600, 10, 260, 400);

        pnlOpciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        btnNuevo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNuevo.setText("Nuevo");

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCancelar.setText("Volver");

        javax.swing.GroupLayout pnlOpcionesLayout = new javax.swing.GroupLayout(pnlOpciones);
        pnlOpciones.setLayout(pnlOpcionesLayout);
        pnlOpcionesLayout.setHorizontalGroup(
            pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOpcionesLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        pnlOpcionesLayout.setVerticalGroup(
            pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcionesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(31, 31, 31))
        );

        getContentPane().add(pnlOpciones);
        pnlOpciones.setBounds(440, 10, 150, 170);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FGestionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FGestionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FGestionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FGestionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FGestionarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox<String> cbGrupo;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JTable dgvDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblSerie;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JPanel pnlAcciones;
    private javax.swing.JPanel pnlBusqueda;
    private javax.swing.JPanel pnlGT;
    private javax.swing.JPanel pnlLista;
    private javax.swing.JPanel pnlOpciones;
    private javax.swing.JPanel pnlProducto;
    private javax.swing.JRadioButton rdCodigo;
    private javax.swing.JRadioButton rdNombre;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtSerie;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
