/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.ingswii.vista;

/**
 *
 * @author Jessy
 */
public class FNuevoGrupo extends javax.swing.JFrame {

    /**
     * Creates new form FNuevoGrupo
     */
    public FNuevoGrupo() {
        initComponents();
        setSize(422, 360);//dar tamano fijo a la pantalla
        setLocationRelativeTo(null);//centrar la pantala 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pnlRegistrar = new javax.swing.JPanel();
        lblGrupo = new javax.swing.JLabel();
        txtGrupo = new javax.swing.JTextField();
        pnlOpciones = new javax.swing.JPanel();
        btnCrearTipo = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        pnlTexto = new javax.swing.JPanel();
        lblTexto = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pnlRegistrar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        pnlRegistrar.setLayout(null);

        lblGrupo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblGrupo.setText("Grupo: ");
        pnlRegistrar.add(lblGrupo);
        lblGrupo.setBounds(80, 50, 41, 15);

        txtGrupo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtGrupo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGrupoKeyTyped(evt);
            }
        });
        pnlRegistrar.add(txtGrupo);
        txtGrupo.setBounds(160, 40, 150, 30);

        getContentPane().add(pnlRegistrar);
        pnlRegistrar.setBounds(10, 57, 390, 100);

        pnlOpciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        pnlOpciones.setLayout(null);

        btnCrearTipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCrearTipo.setText("Crear un nuevo tipo");
        pnlOpciones.add(btnCrearTipo);
        btnCrearTipo.setBounds(120, 100, 150, 30);

        btnNuevo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNuevo.setText("Nuevo");
        pnlOpciones.add(btnNuevo);
        btnNuevo.setBounds(60, 40, 110, 30);

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnGuardar.setText("Volver");
        pnlOpciones.add(btnGuardar);
        btnGuardar.setBounds(230, 40, 110, 30);

        getContentPane().add(pnlOpciones);
        pnlOpciones.setBounds(10, 160, 390, 160);

        pnlTexto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        pnlTexto.setLayout(null);

        lblTexto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTexto.setText("Crear un nuevo Grupo de Producto");
        pnlTexto.add(lblTexto);
        lblTexto.setBounds(80, 10, 220, 14);

        getContentPane().add(pnlTexto);
        pnlTexto.setBounds(12, 10, 390, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGrupoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrupoKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if((c<'A'||c>'Z')){
            evt.consume();
        }
                    
    }//GEN-LAST:event_txtGrupoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FNuevoGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FNuevoGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FNuevoGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FNuevoGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FNuevoGrupo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearTipo;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JPanel pnlOpciones;
    private javax.swing.JPanel pnlRegistrar;
    private javax.swing.JPanel pnlTexto;
    private javax.swing.JTextField txtGrupo;
    // End of variables declaration//GEN-END:variables
}
