/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.ingswii.vista;

/**
 *
 * @author Jessy
 */
public class FNuevoTipo extends javax.swing.JFrame {

    /**
     * Creates new form JNuevoTipo
     */
    public FNuevoTipo() {
        initComponents();
        setSize(416, 336);//dar tamano fijo a la pantalla
        setLocationRelativeTo(null);//centrar la pantala 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTexto = new javax.swing.JPanel();
        lblTexto = new javax.swing.JLabel();
        pnlRegistrar = new javax.swing.JPanel();
        lblGrupo = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        cbGrupo = new javax.swing.JComboBox<>();
        lblGrupo1 = new javax.swing.JLabel();
        pnlOpciones = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pnlTexto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        pnlTexto.setLayout(null);

        lblTexto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTexto.setText("Crear un nuevo Tipo de Producto");
        pnlTexto.add(lblTexto);
        lblTexto.setBounds(80, 10, 220, 14);

        getContentPane().add(pnlTexto);
        pnlTexto.setBounds(5, 10, 390, 40);

        pnlRegistrar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        pnlRegistrar.setLayout(null);

        lblGrupo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblGrupo.setText("Tipo:");
        pnlRegistrar.add(lblGrupo);
        lblGrupo.setBounds(70, 80, 28, 15);

        txtTipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnlRegistrar.add(txtTipo);
        txtTipo.setBounds(150, 80, 150, 30);

        cbGrupo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlRegistrar.add(cbGrupo);
        cbGrupo.setBounds(150, 30, 150, 30);

        lblGrupo1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblGrupo1.setText("Grupo: ");
        pnlRegistrar.add(lblGrupo1);
        lblGrupo1.setBounds(70, 40, 41, 15);

        getContentPane().add(pnlRegistrar);
        pnlRegistrar.setBounds(5, 57, 390, 140);

        pnlOpciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        pnlOpciones.setLayout(null);

        btnNuevo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNuevo.setText("Nuevo");
        pnlOpciones.add(btnNuevo);
        btnNuevo.setBounds(60, 40, 110, 30);

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        pnlOpciones.add(btnGuardar);
        btnGuardar.setBounds(230, 40, 110, 30);

        getContentPane().add(pnlOpciones);
        pnlOpciones.setBounds(5, 203, 390, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FNuevoTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FNuevoTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FNuevoTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FNuevoTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FNuevoTipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cbGrupo;
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JLabel lblGrupo1;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JPanel pnlOpciones;
    private javax.swing.JPanel pnlRegistrar;
    private javax.swing.JPanel pnlTexto;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
